### ISSUE TITLE
tic fails when Add files via upload

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#30] opened 2021-02-03 10:54 UTC
@pat-s is it a dplyr issue?
https://github.com/dsbbfinddx/FINDCov19TrackerData/runs/1821664069?check_suite_focus=true#step:22:119
There is no problem when run locally, all files get updated.

**Comment by dsbb-finddx** [comment] 2021-02-04 11:43
Problem still persists
https://github.com/dsbbfinddx/FINDCov19TrackerData/runs/1830153194?check_suite_focus=true#step:22:8600

**Comment by pat-s** [comment] 2021-02-04 18:56
The issue is [here](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9/R/shiny-data.R#L241-L251) and likely caused by the recent dplyr 1.0.4 update which introduced [some changes](https://cran.r-project.org/web/packages/dplyr/news/news.html) to `across()`. 

@dsbb-finddx Since you wrote this code part, do you mind having a look?

**Comment by dsbb-finddx** [comment] 2021-02-05 11:54
> The issue is [here](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9/R/shiny-data.R#L241-L251) and likely caused by the recent dplyr 1.0.4 update which introduced [some changes](https://cran.r-project.org/web/packages/dplyr/news/news.html) to `across()`.
> 
> @dsbb-finddx Since you wrote this code part, do you mind having a look?

The issue is [here](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/eaf1e53e11cc2a76f417ac804aa39df5b71c6288/R/shiny-data.R#L209)
`mutate()` and `across()` together do not keep all the columns but only the ones specified?
@christophsax wrote this part, I am trying to debug specifying to `.keep="all"` but it does not work.

Can we keep the previous dplyr version?

**Comment by pat-s** [comment] 2021-02-05 13:22
> mutate() and across() together do not keep all the columns but only the ones specified?
@christophsax wrote this part, I am specifying to .keep="all" but it does not work, still does not find 'pop_100k' column needed for the function.

git blame reported your name, that's why I addressed you.

> Can we keep the previous dplyr version?

temporarily but this should be fixed in the foreseeable future. I've pushed [a fix](https://github.com/dsbbfinddx/FINDCov19TrackerData/commit/0c24415f7e4059409a7b9d6d6ac2dd94b67adbcd).

**Comment by dsbb-finddx** [comment] 2021-02-05 13:32
> > mutate() and across() together do not keep all the columns but only the ones specified?
> > @christophsax wrote this part, I am specifying to .keep="all" but it does not work, still does not find 'pop_100k' column needed for the function.
> 
> git blame reported your name, that's why I addressed you.

No problem :) 
I have added on the original code, but that specific part was from @christophsax 

> > Can we keep the previous dplyr version?
> 
> temporarily but this should be fixed in the foreseeable future. I've pushed [a fix](https://github.com/dsbbfinddx/FINDCov19TrackerData/commit/0c24415f7e4059409a7b9d6d6ac2dd94b67adbcd).

Thank you! I agree, this should be fixed and we should use most up to date dplyr version.
However, in the event of doing this for other packages in the future, is it worth of keeping a stable environment, in terms of R version and packages used for the Git actions?

**Comment by pat-s** [comment] 2021-02-06 08:11
WF is fine again.

I'll open a new issue and assign Christoph.

**Closed by pat-s** 2021-02-06 08:11 UTC
